services:

  web:
    build: .
    command: >
      sh -c "
      until python manage.py dbcheck; do
        echo 'Waiting for the database...'
        sleep 1
      done &&
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./fileportal:/opt/fileportal
    working_dir: /opt/fileportal
    ports:
      - "8000:8000"
    depends_on:
      - db
      - minio
    environment:
      - DEBUG=1
      - SECRET_KEY=your_secret_key
  #    - DATABASE_URL=postgres://postgres:password@db:5432/postgres
      - AWS_ACCESS_KEY_ID=minioadmin
      - AWS_SECRET_ACCESS_KEY=minioadmin
      - AWS_STORAGE_BUCKET_NAME=some-bucket-name
      - AWS_S3_ENDPOINT_URL=http://minio:9000
      - AWS_S3_REGION_NAME=us-east-1
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_HOST=db
      - USE_MINIO=true

  db:
    image: postgres:latest
    volumes:
      - ./.data/postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password

  minio:
    image: docker.io/bitnami/minio:2023
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - 'minio_data:/bitnami/minio/data'
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
      - MINIO_DEFAULT_BUCKETS=some-bucket-name

volumes:
  minio_data:
    driver: local